{"status": "broken", "description": "\n    Verify createGroup and setGroupMembers call with non-empty playerIds and areaIds modifies/creates the group\n    by adding/removing the group member and updates the playerIds and areaIds for the targeted group\n    :param module_dut:\n    :param setup_teardown_two_zps:\n    :param groups_in_hh:\n    :param ws_client:\n    :return:\n    ", "labels": [{"name": "tag", "value": "nightly"}, {"name": "tag", "value": "priority3"}, {"name": "tag", "value": "groups_namespaces"}, {"name": "parentSuite", "value": "player.muse"}, {"name": "suite", "value": "test_saved_groups"}, {"name": "host", "value": "a21cc79c5dcb"}, {"name": "thread", "value": "1-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "player.muse.test_saved_groups"}], "stop": 1683043028879, "uuid": "dab6411e-c63f-438c-b553-08b18393614b", "historyId": "118be6161dbf4bd0d500be21f998fe32", "name": "test_saved_groups_union_of_playerIds_and_areaIds_group_member_modification", "start": 1683043028879, "fullName": "player.muse.test_saved_groups#test_saved_groups_union_of_playerIds_and_areaIds_group_member_modification", "statusDetails": {"message": "HTTPError: 401 Client Error: Unauthorized for url: https://oauth.test.ws.sonos.com/auth/oauth/v2/token", "trace": ">       lambda: ihook(item=item, **kwds),\n        when=when,\n    )\n\n../../../.venv/local/lib/python2.7/site-packages/flaky/flaky_pytest_plugin.py:306: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nplugins/muse_plugin.py:313: in ws_client\n    return websocket_manager.make_connection(dut_manager.zp)\n../../../.venv/local/lib/python2.7/site-packages/sonos/museclient/websocket_manager.py:41: in make_connection\n    ws_conn = MuseWebsocketClient(ip=zp.ip, secure=secure, apiKey=apiKey, subprotocols=subprotocols)\n../../../.venv/local/lib/python2.7/site-packages/sonos/museclient/muse_websocket_client.py:13: in __init__\n    subprotocols=subprotocols, fetchToken=fetchToken, secureRegCheck=secureRegCheck)\n../../../.venv/local/lib/python2.7/site-packages/sonos/museclient/base_muse_websocket.py:92: in __init__\n    secureRegCheck=secureRegCheck)\n../../../.venv/local/lib/python2.7/site-packages/sonos/museclient/base_muse_rest.py:82: in __init__\n    self.updateOauthTokens()\n../../../.venv/local/lib/python2.7/site-packages/sonos/museclient/base_muse_rest.py:387: in updateOauthTokens\n    tokenObj = OAuth.get_oauth_token(scope=scopeString, username=username, password=password, use_v4=useV4)\n../../../.venv/local/lib/python2.7/site-packages/retry/api.py:74: in retry_decorator\n    logger)\n../../../.venv/local/lib/python2.7/site-packages/retry/api.py:33: in __retry_internal\n    return f()\n../../../.venv/local/lib/python2.7/site-packages/sonos/oauth/common.py:219: in get_oauth_token\n    res.raise_for_status()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <Response [401]>\n\n    def raise_for_status(self):\n        \"\"\"Raises :class:`HTTPError`, if one occurred.\"\"\"\n    \n        http_error_msg = ''\n        if isinstance(self.reason, bytes):\n            # We attempt to decode utf-8 first because some servers\n            # choose to localize their reason strings. If the string\n            # isn't utf-8, we fall back to iso-8859-1 for all other\n            # encodings. (See PR #3538)\n            try:\n                reason = self.reason.decode('utf-8')\n            except UnicodeDecodeError:\n                reason = self.reason.decode('iso-8859-1')\n        else:\n            reason = self.reason\n    \n        if 400 <= self.status_code < 500:\n            http_error_msg = u'%s Client Error: %s for url: %s' % (self.status_code, reason, self.url)\n    \n        elif 500 <= self.status_code < 600:\n            http_error_msg = u'%s Server Error: %s for url: %s' % (self.status_code, reason, self.url)\n    \n        if http_error_msg:\n>           raise HTTPError(http_error_msg, response=self)\nE           HTTPError: 401 Client Error: Unauthorized for url: https://oauth.test.ws.sonos.com/auth/oauth/v2/token\n\n../../../.venv/local/lib/python2.7/site-packages/requests/models.py:960: HTTPError"}, "attachments": [{"source": "7b55c2bb-deb2-4a3f-897d-55d766d7c387-attachment.txt", "type": "text/plain", "name": "stderr"}]}